name: Deploy release
on:
  release:
    types: [released]

jobs:
  deploy:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - deploy-branch: main

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Required for branch search below.
          fetch-depth: 0

      - name: Get the tag (version)
        id: get-tag
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Verify whether ${{ github.ref }} tags in deploy branch (${{ matrix.deploy-branch }})
        run: |
          BRANCHES=$(git branch -r --contains ${{ github.ref }})

          if [[ echo $BRANCHES | grep -q "origin/${{ matrix.deploy-branch }}" ]]; then
            echo "::error::${{ github.ref }} does not tag a commit in the expected deployment branch (${{ matrix.deploy-branch }}), but instead in: $BRANCHES"
            exit 1
          fi

      - name: Fake PRODUCTION deploy of tag ${{ steps.get-tag.outputs.VERSION }}
        run: echo "Deployed ${{ steps.get-tag.outputs.VERSION }}!"
