name: Deploy release
on:
  release:
    types: [released]

jobs:
  deploy:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the tag (version)
        id: get-tag
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: BROKEN deploy of tag ${{ steps.get-tag.outputs.VERSION }}
        run: exit 1
