name: Deploy release
on:
  release:
    types: [released]

jobs:
  deploy:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - deploy-branch: main

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Required for branch search below.
          fetch-depth: 0

      - name: Get the tag (version)
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Verify whether ${{ steps.get-version.outputs.VERSION }} in (${{ matrix.deploy-branch }})
        run: |
          BRANCHES=$(git branch -r --contains ${{ github.ref }} | xargs echo)
          echo "${{ github.ref }} tags the following branch(es): $BRANCHES"

          DEPLOY_BRANCH_REF="origin/${{ matrix.deploy-branch }}"
          if ! echo $BRANCHES | grep -q "$DEPLOY_BRANCH_REF"
          then
            echo "::error::${{ github.ref }} does not tag a commit in $DEPLOY_BRANCH_REF, but in: $BRANCHES"
            exit 1
          fi

      - name: Fake PRODUCTION deploy of tag ${{ steps.get-version.outputs.VERSION }}
        run: echo "Deployed ${{ steps.get-version.outputs.VERSION }}!"
