name: Deploy release
on:
  release:
    types: [released]

jobs:
  debug:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
     - name: Debugging
       run: echo "${{ github.event.release.target_commitish }}"

  deploy:
    if: github.event.release.target_commitish == 'main'
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy of tag ${{ steps.get-tag.outputs.VERSION }}
        run: exit 0
