name: Deploy release
on:
  release:
    types: [released]

jobs:
  deploy:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - deploy-branch: main

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the tag (version)
        id: get-tag
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Get branch tagged in ${{ steps.get-tag.outputs.VERSION }}
        id: get-tagged-branch
        # This requires "fetch-depth: 0" in the checkout
        run: |
          branches=$(git branch -r --contains ${{ github.ref }} | sed -e 's/origin\///g' | xargs echo)
          echo ::set-output name=BRANCHES::$branches

      - name: Verify whether ${{ steps.get-tag.outputs.VERSION }} is deploy branch
        env:
          $TAGGED_BRANCHES: ${{ steps.get-tagged-branch.outputs.BRANCHES }}
          DEPLOY_BRANCH: ${{ matrix.deploy-branch }}
        run: |
          if [[ **"$TAGGED_BRANCHES"** != "$DEPLOY_BRANCH" ]]
          then
            echo "::error::${{ steps.get-tag.outputs.VERSION }} does not tag a commit in the expected deployment branch ($DEPLOY_BRANCH), but instead in: $TAGGED_BRANCHES"
            exit 1
          fi

      - name: Fake PRODUCTION deploy of tag ${{ steps.get-tag.outputs.VERSION }}
        run: echo "Deployed ${{ steps.get-tag.outputs.VERSION }}!"
