name: Tag release
on:
  push:
    branches:
      - main

jobs:
  deploy:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Required for semantic-release

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Release
        env:
          GITHUB_TOKEN: DUMMY-TOKEN
        run: npx semantic-release --branches main
